from pathlib import Path

# Default parser attributes
default_gff_filter = "CDS"
default_amr_filter = "AMR"

# Basic set of columns to emit
default_output_columns = [
    "BioSample_ID",
    "assembly_ID",
    "genus",
    "species",
    "organism",
    "isolate",
    "taxon_id",
    "region",
    "region_start",
    "region_end",
    "strand",
    "_bin",
    "id",
    "gene_symbol",
    "amr_element_symbol",
    "element_type",
    "element_subtype",
    "class",
    "subclass",
    "split_subclass",
    "antibiotic_name",
    "antibiotic_abbreviation",
    "antibiotic_ontology",
    "antibiotic_ontology_link",
    "evidence_accession",
    "evidence_type",
    "evidence_link",
    "evidence_description",
]

# Mapping of output column names to GFF attribute names if different
default_conversion_field_names = {
    "id": "ID",
    "gene_symbol": "Name",
    "amr_element_symbol": "amrfinderplus_element_symbol",
    "amr_element_name": "amrfinderplus_element_name",
    "class": "drug_class",
    "subclass": "drug_subclass",
    "_bin": "bin",
}

# Modified columns to exclude assembly related fields to ensure we do not overwrite them with incorrect data
assembly_fields = [
    "BioSample_ID",
    "assembly_ID",
    "taxon_id",
    "genus",
    "species",
    "organism",
    "isolate",
    "phenotype",
    "genotype",
]
# Just moving these out as they became part of the assembly table which was odd
_region_fields = [
    "region",
    "region_start",
    "region_end",
    "strand",
    "_bin",
]
default_feature_fields = [
    c for c in default_output_columns if c not in assembly_fields + _region_fields
]

parquet = {
    "compression": "zstd",
    "compression_level": 3,
}

species_names_override = {
    "Salmonella enterica subsp. enterica serovar Kentucky": "Salmonella enterica",
    "Salmonella enterica subsp. enterica serovar Hadar": "Salmonella enterica",
}

antibiotics_config = Path(__file__).parent.parent / "configs" / "antibiotics.csv"

# Taken from CABBAGE antibiograms
# antibiotic_acrynoyms = {
#     "amikacin": "AMK",
#     "ampicillin": "AMP",
#     "ampicillin-sulbactam": "SAM",
#     "aztreonam": "ATM",
#     "cefazolin": "CZO",
#     "cefepime": "FEP",
#     "cefotaxime": "CTX",
#     "cefoxitin": "FOX",
#     "ceftazidime": "CAZ",
#     "ceftriaxone": "CRO",
#     "ciprofloxacin": "CIP",
#     "doripenem": "DOR",
#     "ertapenem": "ETP",
#     "gentamicin": "GEN",
#     "imipenem": "IPM",
#     "levofloxacin": "LVX",
#     "meropenem": "MEM",
#     "minocycline": "MNO",
#     "nitrofurantoin": "NIT",
#     "piperacillin": "PIP",
#     "piperacillin-tazobactam": "TZP",
#     "tetracycline": "TCY",
#     "ticarcillin-clavulanic acid": "TCC",
#     "tigecycline": "TGC",
#     "tobramycin": "TOB",
#     "trimethoprim-sulfamethoxazole": "SXT",
# }

custom_antibiotic_acronyms = {
    "kanamycin A": "KAN",
}

antibiotic_acrynoyms = {
    "amikacin": "AMK",
    "aminoglycosides": None,
    "amoxicillin": "AMX",
    "amoxicillin/clavulanic acid": "AMC",
    "ampicillin": "AMP",
    "ampicillin/sulbactam": "SAM",
    "apramycin": "APR",
    "arbekacin": "ARB",
    "avilamycin": "AVI",
    "azidothymidine": None,
    "azithromycin": "AZM",
    "aztreonam": "ATM",
    "bacitracin zinc": "BAC",
    "bedaquiline": "BDQ",
    "beta-lactams": None,
    "biapenem": "BIA",
    "capreomycin": "CAP",
    "carbapenems": None,
    "carbenicillin": "CRB",
    "cefaclor": "CEC",
    "cefamandole": "MAN",
    "cefatrizine": "CTZ",
    "cefazolin": "CZO",
    "cefepime": "FEP",
    "cefepime/taniborbactam": None,
    "cefepime/zidebactam": "FPZ",
    "cefiderocol": "FDC",
    "cefixime": "CFM",
    "cefmetazole": "CMZ",
    "cefoperazone": "CFP",
    "cefoperazone/sulbactam": "CSL",
    "cefotaxime": "CTX",
    "cefotaxime/clavulanic acid": "CTC",
    "cefotetan": "CTT",
    "cefovecin": "FOV",
    "cefoxitin": "FOX",
    "cefozopran": "ZOP",
    "cefpimizole": "CFZ",
    "cefpirome": "CPO",
    "cefpodoxime": "CPD",
    "cefpodoxime/clavulanic acid": "CDC",
    "cefquinome": "CEQ",
    "ceftaroline": "CPT",
    "ceftazidime": "CAZ",
    "ceftazidime/avibactam": "CZA",
    "ceftazidime/clavulanic acid": "CCV",
    "ceftibuten": "CTB",
    "ceftiofur": "TIO",
    "ceftizoxime": "CZX",
    "ceftolozane/tazobactam": "CZT",
    "ceftriaxone": "CRO",
    "ceftriaxone/cefpodoxime": None,
    "cefuroxime": "CXM",
    "cephalexin": "LEX",
    "cephalosporins": None,
    "cephalothin": "CEP",
    "chloramphenicol": "CHL",
    "chlortetracycline": "CTE",
    "ciprofloxacin": "CIP",
    "clarithromycin": "CLR",
    "clindamycin": "CLI",
    "clofazimine": "CLF",
    "clotrimazole": "CTR",
    "colistin": "COL",
    "cycloserine": "CYC",
    "dalbavancin": "DAL",
    "danofloxacin": "DAN",
    "daptomycin": "DAP",
    "delafloxacin": "DFX",
    "delamanid": "DLM",
    "dicloxacillin": "DIC",
    "doripenem": "DOR",
    "doxycycline": "DOX",
    "enrofloxacin": "ENR",
    "eravacycline": "ERV",
    "ertapenem": "ETP",
    "erythromycin": "ERY",
    "ethambutol": "ETH",
    "ethionamide": "ETI1",
    "fidaxomicin": "FDX",
    "florfenicol": "FLR",
    "fluconazole": "FLU",
    "fluoroquinolones": None,
    "fosfomycin": "FOS",
    "furazolidone": "FRZ",
    "fusidic acid": "FUS",
    "gatifloxacin": "GAT",
    "gemifloxacin": "GEM",
    "gentamicin": "GEN",
    "imipenem": "IPM",
    "imipenem/edta": "IPE",
    "imipenem/relebactam": "IMR",
    "isoniazid": "INH",
    "kanamycin": "KAN",
    "levofloxacin": "LVX",
    "lincomycin": "LIN",
    "linezolid": "LNZ",
    "marbofloxacin": "MAR",
    "mecillinam": "MEC",
    "meropenem": "MEM",
    "meropenem/vaborbactam": "MEV",
    "methicillin": "MET",
    "metronidazole": "MTR",
    "mezlocillin": "MEZ",
    "minocycline": "MNO",
    "moxifloxacin": "MFX",
    "mupirocin": "MUP",
    "nafcillin": "NAF",
    "nalidixic acid": "NAL",
    "neomycin": "NEO",
    "netilmicin": "NET",
    "nicotinamide": None,
    "nitrofurantoin": "NIT",
    "norfloxacin": "NOR",
    "novobiocin": "NOV",
    "ofloxacin": "OFX",
    "omadacycline": "OMC",
    "orbifloxacin": "ORB",
    "oxacillin": "OXA",
    "oxytetracycline": "OXY",
    "p-aminosalicylic acid": "PAS",
    "pefloxacin": "PEF",
    "penicillin": "PEN",
    "penicillin/clavulanic acid": None,
    "pentizidone": "PTZ",
    "piperacillin": "PIP",
    "piperacillin/tazobactam": "TZP",
    "plazomicin": "PLZ",
    "polymyxin": None,
    "polymyxin b": "PLB",
    "pradofloxacin": "PRA",
    "pretomanid": "PMD",
    "prothionamide": "PTH",
    "pyrazinamide": "PZA",
    "pyrazinamide/nicotinamide": None,
    "quinupristin/dalfopristin": "QDA",
    "rifabutin": "RIB",
    "rifampicin": "RIF",
    "rifaximin": "RFX",
    "sparfloxacin": "SPX",
    "spectinomycin": "SPT",
    "spiramycin": "SPI",
    "streptoduocin": "STR",
    "streptomycin": "STR1",
    "sulbactam": "SUL",
    "sulfadimethoxine": "SUD",
    "sulfafurazole": "SLF",
    "sulfamethoxazole": "SMX",
    "sulfathiazole": "SUT",
    "sulfisoxazole": "SOX",
    "sulfonamide": "SSS",
    "sulfonamides": None,
    "surotomycin": "SUR",
    "tedizolid": "TZD",
    "teicoplanin": "TEC",
    "telavancin": "TLV",
    "telithromycin": "TLT",
    "temocillin": "TEM",
    "tetracycline": "TCY",
    "tetroxoprim": "TET",
    "tiamulin": "TIA",
    "ticarcillin": "TIC",
    "ticarcillin/clavulanic acid": "TCC",
    "tigecycline": "TGC",
    "tilmicosin": "TIL",
    "tobramycin": "TOB",
    "trimethoprim": "TMP",
    "trimethoprim/sulfamethoxazole": "SXT",
    "trimethoprim/sulfobactam": None,
    "trimethoprim/sulfonamide": None,
    "trovafloxacin": "TVA",
    "tulathromycin": "TUL",
    "tylosin": "TYL",
    "vancomycin": "VAN",
    "voriconazole": "VOR",
    "zoliflodacin": "ZFD",
} | custom_antibiotic_acronyms
